Update main_swigyweb.yml

diff --git a/.github/workflows/main_swigyweb.yml b/.github/workflows/main_swigyweb.yml
--- a/.github/workflows/main_swigyweb.yml
+++ b/.github/workflows/main_swigyweb.yml
@@ -9,8 +9,8 @@ on:
       - "main"
 
 jobs:
-  deploy:
-    runs-on: ubuntu-latest
+  build:
+    runs-on: self-hosted
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -47,52 +47,45 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1
 
-      - name: Install Trivy
-        run: |
-          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.39.0/trivy_0.39.0_Linux-64bit.deb -o trivy.deb
-          sudo dpkg -i trivy.deb
+      # - name: Install Trivy
+      #   run: |
+      #     curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.39.0/trivy_0.39.0_Linux-64bit.deb -o trivy.deb
+      #     sudo dpkg -i trivy.deb
 
       - name: Trivy filesystem scan
         run: |
           trivy fs --format table -o fs-report.html .
 
-      # OWASP Dependency-Check
-      - name: Install OWASP Dependency-Check
-        run: |
-          wget https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.1/dependency-check-11.1.1-release.zip
-          if [ ! -f dependency-check-11.1.1-release.zip ]; then
-            echo "Error: Dependency-Check zip file download failed!"
-            exit 1
-          fi
-          file_size=$(stat -c %s dependency-check-11.1.1-release.zip)
-          if [ "$file_size" -le 0 ]; then
-            echo "Error: The downloaded file is empty!"
-            exit 1
-          fi
-          if ! unzip -t dependency-check-11.1.1-release.zip; then
-            echo "Error: Invalid zip file."
-            exit 1
-          fi
-          unzip dependency-check-11.1.1-release.zip
-          ls -al
-          if [ ! -d "dependency-check" ]; then
-            echo "Error: dependency-check directory not found!"
-            exit 1
-          fi
-          cd dependency-check
-          ./bin/dependency-check.sh --version
+      # # OWASP Dependency-Check
+      # - name: Install OWASP Dependency-Check
+      #   run: |
+      #     wget https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.1/dependency-check-11.1.1-release.zip
+      #     if [ ! -f dependency-check-11.1.1-release.zip ]; then
+      #       echo "Error: Dependency-Check zip file download failed!"
+      #       exit 1
+      #     fi
+      #     file_size=$(stat -c %s dependency-check-11.1.1-release.zip)
+      #     if [ "$file_size" -le 0 ]; then
+      #       echo "Error: The downloaded file is empty!"
+      #       exit 1
+      #     fi
+      #     if ! unzip -t dependency-check-11.1.1-release.zip; then
+      #       echo "Error: Invalid zip file."
+      #       exit 1
+      #     fi
+      #     unzip dependency-check-11.1.1-release.zip
+      #     ls -al
+      #     if [ ! -d "dependency-check" ]; then
+      #       echo "Error: dependency-check directory not found!"
+      #       exit 1
+      #     fi
+      #     cd dependency-check
+      #     ./bin/dependency-check.sh --version
 
-      - name: Run OWASP Dependency-Check
-        run: |
-          cd dependency-check
-          ./bin/dependency-check.sh --project "NodeJS App" --scan . --out ./dependency-check-report --format XML
-
-      # Upload OWASP Dependency-Check report
-      - name: Upload OWASP Dependency-Check report
-        uses: actions/upload-artifact@v3
-        with:
-          name: dependency-check-report
-          path: ./dependency-check-report/dependency-check-report.xml
+      # - name: Run OWASP Dependency-Check
+      #   run: |
+      #     cd dependency-check
+      #     ./bin/dependency-check.sh --project "NodeJS App" --scan . --out ./dependency-check-report --format XML
           
       # Code Scan For SonarQube    
       - name: SonarQube Scan
