Update main_swigyweb.yml

diff --git a/.github/workflows/main_swigyweb.yml b/.github/workflows/main_swigyweb.yml
--- a/.github/workflows/main_swigyweb.yml
+++ b/.github/workflows/main_swigyweb.yml
@@ -45,12 +45,24 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1
           
-      # SonarQube Scan Job
       - name: SonarQube Scan
         uses: sonarsource/sonarqube-scan-action@master
         env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Add your SonarQube Token in GitHub Secrets
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Use your SonarQube URL
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+          
+      - name: SonarQube Quality Gate check
+        id: quality-gate
+        uses: sonarsource/sonarqube-quality-gate-action@master
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+      - name: Fail if Quality Gate fails
+        if: steps.quality-gate.outputs.quality_gate_status != 'passed'
+        run: |
+          echo "SonarQube Quality Gate failed!"
+          exit 1
 
       - name: Create ECR repository (if not exists)
         run: |
